application: minisnippets	#FIX ME
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/snippets@.*minisnippets\.appspotmail\.com	#FIX ME
  script: receive_email.py
  login: admin

- url: .*
  script: main.py
  secure: always
    
inbound_services:
- mail